# Generated by Django 5.2.7 on 2026-03-06 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Africa', 'Africa'), ('Europe', 'Europe'), ('Asia', 'Asia'), ('Americas', 'Americas')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('schools_discovered', models.IntegerField(default=0)),
                ('staff_extracted', models.IntegerField(default=0)),
                ('research_centres_found', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('region', models.CharField(choices=[('Africa', 'Africa'), ('Europe', 'Europe'), ('Asia', 'Asia'), ('Americas', 'Americas')], default='Africa', max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
                ('programmes', models.TextField(blank=True, help_text='Semicolon-separated list of programmes')),
                ('programme_count', models.IntegerField(default=0)),
                ('phd_count', models.IntegerField(default=0)),
                ('masters_count', models.IntegerField(default=0)),
                ('mba_count', models.IntegerField(default=0)),
                ('bachelor_count', models.IntegerField(default=0)),
                ('research_centres', models.TextField(blank=True, help_text='Semicolon-separated research centres')),
                ('research_themes', models.TextField(blank=True, help_text='Semicolon-separated research themes')),
                ('research_centre_count', models.IntegerField(default=0)),
                ('academic_staff_count', models.IntegerField(default=0)),
                ('total_staff_extracted', models.IntegerField(default=0)),
                ('accreditation', models.CharField(blank=True, help_text='e.g., AACSB, EQUIS, AMBA', max_length=500)),
                ('source', models.CharField(default='Verified Database', max_length=100)),
                ('discovered_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Business Schools',
                'indexes': [models.Index(fields=['country', 'region'], name='health_app__country_b5d961_idx'), models.Index(fields=['region'], name='health_app__region_32c9b1_idx'), models.Index(fields=['phd_count'], name='health_app__phd_cou_b286b5_idx'), models.Index(fields=['masters_count'], name='health_app__masters_6202d6_idx')],
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='ResearchCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('theme', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('discovered_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_centres_data', to='health_app.businessschool')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'theme'], name='health_app__school__50545b_idx'), models.Index(fields=['theme'], name='health_app__theme_907edb_idx')],
                'unique_together': {('name', 'school')},
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('degree', models.CharField(choices=[('phd', 'PhD'), ('masters', 'Masters'), ('mba', 'MBA'), ('bachelor', 'Bachelor'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('research_interests', models.TextField(blank=True, help_text='Semicolon-separated research interests')),
                ('orcid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('profile_url', models.URLField(blank=True, null=True)),
                ('discovered_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='health_app.businessschool')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'degree'], name='health_app__school__05d9f0_idx'), models.Index(fields=['degree'], name='health_app__degree_d896a4_idx'), models.Index(fields=['name'], name='health_app__name_16911c_idx')],
                'unique_together': {('name', 'school')},
            },
        ),
    ]
