# Generated by Django 5.2.7 on 2026-03-06 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessschool',
            name='programmes',
        ),
        migrations.AlterField(
            model_name='businessschool',
            name='website',
            field=models.URLField(blank=True, help_text="School's official website URL - used as source", null=True),
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Actual programme name (e.g., 'MBA in Finance', 'PhD in Management')", max_length=300)),
                ('level', models.CharField(choices=[('bachelor', 'Bachelor'), ('mba', 'MBA'), ('masters', 'Masters'), ('phd', 'PhD'), ('executive', 'Executive'), ('postgraduate', 'Postgraduate'), ('other', 'Other')], help_text='Programme level/type', max_length=20)),
                ('source_url', models.URLField(blank=True, help_text='Direct URL to programme page on school website', null=True)),
                ('discovered_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='health_app.businessschool')),
            ],
            options={
                'verbose_name_plural': 'Programmes',
                'indexes': [models.Index(fields=['school', 'level'], name='health_app__school__feb1bf_idx'), models.Index(fields=['level'], name='health_app__level_d9197c_idx'), models.Index(fields=['name'], name='health_app__name_992395_idx')],
                'unique_together': {('school', 'name', 'level')},
            },
        ),
    ]
