# Generated by Django 5.2.7 on 2026-03-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0002_remove_businessschool_programmes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessschool',
            name='continent',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Oceania', 'Oceania')], db_index=True, default='Africa', help_text='Continent for global normalization', max_length=50),
        ),
        migrations.AlterField(
            model_name='businessschool',
            name='region',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Europe', 'Europe'), ('Asia', 'Asia'), ('Americas', 'Americas'), ('Oceania', 'Oceania')], default='Africa', help_text='Regional grouping', max_length=50),
        ),
        migrations.AddIndex(
            model_name='businessschool',
            index=models.Index(fields=['continent', 'country'], name='health_app__contine_e5bfc8_idx'),
        ),
    ]
